name: linuxserver-tvheadend
services:
  app:
    cpu_shares: 90
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - RUN_OPTS=
    image: linuxserver/tvheadend:version-653bd040
    labels:
      icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tvheadend-big.png
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/recordings:/recordings
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use, see this list.
        - container: RUN_OPTS
          description:
            en_us: Optionally specify additional arguments to be passed. See Additional
              runtime parameters.
    networks: host
x-casaos:
  architectures:
    - amd64
    - arm64
  category: LinuxServer.io
  description:
    en_us: "Tvheadend works as a proxy server: is a TV streaming server and recorder
      for Linux, FreeBSD and Android supporting DVB-S, DVB-S2, DVB-C, DVB-T,
      ATSC, ISDB-T, IPTV, SAT>IP and HDHomeRun as input sources. Tvheadend
      offers the HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and SAT>IP streaming.
      Multiple EPG sources are supported (over-the-air DVB and ATSC including
      OpenTV DVB extensions, XMLTV, PyXML)."
  developer: LinuxServer.io
  hostname: ""
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tvheadend-big.png
  index: /
  is_uncontrolled: false
  main: app
  port_map: "9981"
  scheme: http
  tagline:
    en_us: "Works as a proxy server: is a TV streaming server and recorder for
      Linux, FreeBSD and Android supporting DVB-S, DVB-S2, DVB-C, DVB-T, ATSC,
      ISDB-T, IPTV, SAT>IP and HDHomeRun as input sources. Tvheadend offers the
      HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and SAT>IP streaming. Multiple
      EPG sources are supported (over-the-air DVB and ATSC including OpenTV DVB
      extensions, XMLTV, PyXML)."
  thumbnail: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/tvheadend-big.png
  title:
    custom: ""
    en_us: Tvheadend
