name: nextpvr
services:
  nextpvr:
    cpu_shares: 90
    container_name: nextpvr
    environment:
      #- HOST_IP=127.0.0.1 # Enable for HDHomerun users.
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    hostname: nextpvr
    image: nextpvr/nextpvr_amd64:stable
    labels:
      icon: https://www.nextpvr.com/favicon.png
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/buffer:/buffer
      - /DATA/Media/Recordings:/recordings
    ports: []
    # Enable ports if you do not use HDHomerun.
    #  - 8866:8866
    #  - 16891:16891/udp
    #  - 8026:8026/udp
    network_mode: host  # If you have an HDHomeRun, you must use 'host' network mode so that HDHomeRun can multicast to your app.
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://www.nextpvr.com/favicon.png
  index: /
  is_uncontrolled: false
  port_map: "8866"
  scheme: http
  title:
    custom: NextPVR
    en_us: nextpvr
  tips:
    before_install:
      en_us: |
        The default login is 'admin/password'.
        Note for HDHomeRun users. In order for the HDHomeRun to stream to your containers, you must specify the environment variable `HOST_IP` to the ip of your host.
        For example, if you hosts your docker container on 1.2.3.4, you must set `HOST_IP=1.2.3.4`
        