name: nextpvr
services:
  nextpvr:
    cpu_shares: 90
    container_name: nextpvr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    hostname: nextpvr
    image: nextpvr/nextpvr_amd64:stable
    labels:
      icon: https://www.nextpvr.com/favicon.png
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/buffer:/buffer
      - /DATA/Media/Recordings:/recordings
    ports: []
    network_mode: host
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://www.nextpvr.com/favicon.png
  index: /
  is_uncontrolled: false
  port_map: "8866"
  scheme: http
  title:
    custom: NextPVR
    en_us: nextpvr
  tips:
    before_install:
      en_us: |
        The default login is 'admin/password'.
        This is a configuration for HDHomeRun users. In order for the HDHomeRun to stream to your containers, you must setup your docker container to be on hte host network.
        This is because the HDHomeRun will stream back to NextPVR on different unpredictable ports (a.k.a. a very wide range of non-sequential ports).
        