name: nextpvr
services:
  nextpvr:
    cpu_shares: 90
    container_name: nextpvr
    environment:
      - HOST_IP=1.2.3.4
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    hostname: nextpvr
    image: nextpvr/nextpvr_amd64:stable
    labels:
      icon: https://www.nextpvr.com/favicon.png
    restart: unless-stopped
    volumes:
      - /DATA/AppData/$AppID/config:/config
      - /DATA/AppData/$AppID/buffer:/buffer
      - /DATA/Media/Recordings:/recordings
    ports:
      - 8866:8866           # Web UI
      - 16891:16891/udp     # NextPVR discovery port
      - 8026:8026/udp
      - 5000:5000/udp       # LIRC for IR on HD Homerun
      - 5002:5002/udp       # Video stream on HD Homerun
      - 5004:5004/udp       # Video stream on HD Homerun
    network_mode: bridge
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://www.nextpvr.com/favicon.png
  index: /
  is_uncontrolled: false
  port_map: "8866"
  scheme: http
  title:
    custom: NextPVR
    en_us: nextpvr
  tips:
    before_install:
      en_us: |
        The default login is 'admin/password'.
        This is a configuration for HDHomeRun users. In order for the HDHomeRun to stream to your containers, you must specify the environment variable `HOST_IP` to the ip of your host.
        For example, if you hosts your docker container on 1.2.3.4, you must set `HOST_IP=1.2.3.4`.
        